#!/bin/sh

DIR="${PARAM:-.}"

for F in $DIR/*.flac; do
    MP3="$DIR/$(basename "$F" .flac).mp3"
    flac -s -c -d "$F" | lame --silent --preset standard - "$MP3"
    `dirname $0`/vcid3 "$F" "$MP3"
done
